# Generated by Django 3.1.4 on 2020-12-12 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookHallRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity_needed', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('request_confirmed_by_user', models.BooleanField(default=False)),
                ('is_alloted', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BookHall',
        ),
        migrations.AddField(
            model_name='booked',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
        migrations.AddField(
            model_name='booked',
            name='hallrequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.bookhallrequest'),
        ),
    ]
