# Generated by Django 3.1.4 on 2020-12-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_auto_20201212_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='is_booked',
        ),
    ]
