# Generated by Django 3.1.4 on 2020-12-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_auto_20201212_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
